apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lvtx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lvtx
    app.kubernetes.io/part-of: ci1t-830-0081-app
  name: devfile-sample-lvtx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lvtx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lvtx
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0081-tenant/ci1t-830-0081-app/devfile-sample-lvtx@sha256:61c2d21bcdf51730ac8563f9cf7afe0092b1bd93f8dd88a04c7e11dc4148c20d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
